export const RECEIVE_LISTINGS = 'RECEIVE_LISTINGS';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const UPDATE_DISPLAY = 'UPDATE_DISPLAY';
export const RECEIVE_USER = "RECEIVE_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOGGED_IN = "LOGGED_IN"

